ToDoList/Models/CategoryModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class CategoryModel
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
    }
}

ToDoList/Models/CreateTaskModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class CreateTaskModel
    {
        public int Id { get; set; } = 0!;

        public required string Task { get; set; }
 
        public required string DataTime { get; set; }
  
        public int CategoryId { get; set; }

        public bool IsCompleted { get; set; }
    }
}

ToDoList/Models/CreateTaskModelwithId.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class CreateTaskModelwithId
    {
        public string Id { get; set; }
        public string Task { get; set; }

        public string DataTime { get; set; }

        public int CategoryId { get; set; }

        public bool IsCompleted { get; set; }

    }
}

ToDoList/Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList/Models/TaskModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class TaskModel
    {
        public int Id { get; set; }
        public string MyTask { get; set; }

        public DateTime DueDate { get; set; }

        public TimeSpan DueTimeSpan { get; set; }

        public int CategoryId { get; set; }

        public string CategoryName { get; set; }

        public bool IsCompleted { get; set; }

    }
}

ToDoList/Models/ToDoListModelVM.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class ToDoListModelVM
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a task")]
        public string MyTask { get; set; }

        [Required(ErrorMessage = "Please enter a date")]
        public DateTime DueDate { get; set; }

        [Required(ErrorMessage = "Select category")]
        public int CategoryId { get; set; }
        public string? DueDateString { get; set; }
        public List<TaskModel>? AllTaskNow { get; set; }
        public List<TaskModel>? AllTaskPast { get; set; }
        public List<TaskModel>? AllTaskFuture { get; set; }
        public List<SelectListItem>? Category { get; set; }
    }
}

ToDoList/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using ToDoList.Services;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace ToDoList.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly Service _Service;

        public ToDoListController()
        {
            _Service = StoreXML.GetStorage() ? new SQLService() : new XMLService();
        }

        public IActionResult Index()
        {
            ViewData["DB"] = StoreXML.GetStorage() ? "SQL" : "XML";

            List<TaskModel> getalltask = _Service.AllTask();
            List<CategoryModel> category = _Service.GetAllCategory();
            List<SelectListItem> categorySelectList = new();

            foreach (CategoryModel item in category)
            {
                categorySelectList.Add(new SelectListItem
                {
                    Text = item.CategoryName,
                    Value = item.Id.ToString(),
                });
            }

            List<TaskModel> taskNow = new();
            List<TaskModel> taskPast = new();
            List<TaskModel> taskFuture = new();

            foreach (var item in getalltask)
            {
                if (item.DueTimeSpan.TotalMinutes < 0 || item.IsCompleted)
                    taskPast.Add(item);
                else if (item.DueTimeSpan.TotalMinutes > 120 && !item.IsCompleted)
                    taskFuture.Add(item);
                else if (item.DueTimeSpan.TotalMinutes > 0 && item.DueTimeSpan.TotalMinutes < 120 && !item.IsCompleted)
                    taskNow.Add(item);
            }

            taskPast.Reverse();

            ToDoListModelVM init = new()
            {
                DueDate = DateTime.Now,
                Category = categorySelectList,
                AllTaskNow = taskNow,
                AllTaskFuture = taskFuture,
                AllTaskPast = taskPast,
            };
            return View(init);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(int? id)
        {

            List<TaskModel> getalltask = _Service.AllTask();
            List<CategoryModel> category = _Service.GetAllCategory();
            List<SelectListItem> CategorySelectList = new();

            foreach (CategoryModel item in category)
            {
                CategorySelectList.Add(new SelectListItem
                {
                    Text = item.CategoryName,
                    Value = item.Id.ToString(),
                });
            }

            List<TaskModel> TaskNow = new();
            List<TaskModel> TaskPast = new();
            List<TaskModel> TaskFuture = new();

            foreach (var item in getalltask)
            {
                if (item.DueTimeSpan.TotalMinutes < 0)
                    TaskPast.Add(item);
                else if (item.DueTimeSpan.TotalMinutes > 120)
                    TaskFuture.Add(item);
                else if (item.DueTimeSpan.TotalMinutes > 0
                    && item.DueTimeSpan.TotalMinutes < 120)

                    TaskNow.Add(item);
            }

            TaskPast.Reverse();

            ToDoListModelVM init = new()
            {
                Category = CategorySelectList,
                AllTaskNow = TaskNow,
                AllTaskFuture = TaskFuture,
                AllTaskPast = TaskPast,
            };

            if (id != null)
            {
                TaskModel oneTaskById = _Service.GetOne((int)id);
                init.Id = oneTaskById.Id;
                init.MyTask = oneTaskById.MyTask;
                init.CategoryId = oneTaskById.CategoryId;
                init.DueDate = oneTaskById.DueDate;
                init.DueDateString =
                    DateTime.ParseExact(oneTaskById.DueDate.ToString(), "dd.MM.yyyy HH:mm:ss", null)
                    .ToString("yyyy-MM-ddTHH:mm:ss");
            }

            return View(init);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddTask(ToDoListModelVM model)
        {
            if (ModelState.IsValid)
            {
                TimeSpan DueTimeSpan = model.DueDate - DateTime.Now;
                string dataActual = DueTimeSpan.TotalMinutes < 0
                    ? DateTime.Now.ToString()
                    : model.DueDate.ToString();

                CreateTaskModel newTask = new()
                {
                    Task = model.MyTask,
                    DataTime = dataActual,
                    CategoryId = model.CategoryId,
                    IsCompleted = false,
                };
                if (model.Id != 0)
                {
                    _Service.UpdateTask(model.Id, newTask);
                    return RedirectToAction("Index");
                }
                _Service.AddTask(newTask);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SetIsCompleted(int id)
        {
            _Service.IsCompleted(id, true, DateTime.Now.ToString());
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SetServise(int id)
        {
            StoreXML.SetStorage(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SetUnCompleted(int id)
        {
            _Service.IsCompleted(id, false, DateTime.Now.ToString());
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTask(int id)
        {
            _Service.DeleteTask(id);
            return RedirectToAction("Index");
        }
    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/css/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/mainstyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Rowdies:wght@300;400;700&display=swap"
          rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Seymour+One&display=swap"
          rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Seymour+One&display=swap"
          rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/Shared/_OneTask.cshtml
@model ToDoList.Models.TaskModel

<div class="resultpage-item">

    <div class="resultpage-item-header">
        <p class="resultpage-item-header-categoryname"><strong> @Model.CategoryName</strong></p>

        <div class="resultpage-item-header-btn">
            
            <form asp-controller="ToDoList" asp-action="DeleteTask" method="post">
                <input type="hidden" name="id" value="@Model.Id" />
                <button title="ОБЕРЕЖНО! ВИДАЛЕННЯ БЕЗ ПІДТВЕРДЖЕННЯ" class="delete" type="submit">Delete</button>
            </form>
            <form asp-controller="ToDoList" asp-action="Index" method="post">
                <input type="hidden" name="id" value="@Model.Id" />
                <button class="update" type="submit">Update</button>
            </form>
            @if (!Model.IsCompleted)
            {
                <form asp-controller="ToDoList" asp-action="SetIsCompleted" method="post">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button class="completedbtn" title="set completed" type="submit">☐</button>
                </form>
            }
            else
            {
                <form asp-controller="ToDoList" asp-action="SetUnCompleted" method="post">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button class="completedbtn" title="set uncompleted" type="submit">✔</button>
                </form>
            }
        </div>
    </div>
    <div style="padding: 5px;">
        @if (Model.DueTimeSpan.TotalMinutes < 0 || Model.IsCompleted)
        {
            <p>Завдання: <s>@Model.MyTask</s></p>
        }
        else
        {
            <p><strong>Завдання: </strong>@Model.MyTask</p>
        }
        <br />
        <p class="textforint textforintdark">
            <strong>
                Дата виконання:
            </strong>@Model.DueDate.Day/@Model.DueDate.Month/@Model.DueDate.Year  <strong>
                @Model.DueDate.Hour:@(Model.DueDate.Minute < 9 ? "0" + Model.DueDate.Minute : Model.DueDate.Minute)
            </strong>
        </p>

    </div>


    @if (Model.DueTimeSpan.TotalMinutes > 120 && !Model.IsCompleted)
    {
        <div style="background: green; width: 100%; padding: 5px;">
            <p class="textforint">
                <strong>Залишилось:</strong>
                @Model.DueTimeSpan.Days дн.,
                @Model.DueTimeSpan.Hours год.,
                @Model.DueTimeSpan.Minutes хв.
            </p>
        </div>

    }
    else if (Model.DueTimeSpan.TotalMinutes < 0 || Model.IsCompleted)
    {

            @if (Model.IsCompleted)
            {
            <div style="background: cornflowerblue; width: 100%; padding: 5px;">

                <p class="textforint">
                    <strong>Виконано!</strong>
                </p>
            </div>
            }
            else if (!Model.IsCompleted)
            {
            <div style="background: maroon; width: 100%; padding: 5px;">
                <p class="textforint">
                    <strong>Закінчилося:</strong>
                    @Math.Abs(Model.DueTimeSpan.Days)  дн.,
                    @Math.Abs(Model.DueTimeSpan.Hours) год.,
                    @Math.Abs(Model.DueTimeSpan.Minutes) хв. тому
                </p>
            </div>
            }       
    }
    else if (Model.DueTimeSpan.TotalMinutes > 0 && Model.DueTimeSpan.TotalMinutes < 120 && !Model.IsCompleted)
    {
        <div style="background:orangered; width: 100%; padding: 5px;">
            <p class="textforint">
                <strong>Залишилось:</strong>
                @Model.DueTimeSpan.Days дн.,
                @Model.DueTimeSpan.Hours год.,
                @Model.DueTimeSpan.Minutes хв.
            </p>
        </div>

    }
</div>

ToDoList/Views/Submit/Index.cshtml
@model ToDoList.Models.SubmitModelVM

@{
    ViewData["Title"] = "Form";
}

<div class="submitpage">
    <div class="submitpage-headerbox">
        <a asp-action="Index">
            <div class="submitpage-headerbox-logobox">
                <img class="submitpage-headerbox-logo" src="~/todoListLogo.svg" />
            </div>
        </a>
        <div class="selectdb">
        <form asp-controller="Submit" asp-action="SetServise" method="post">
            <select asp-for="id">
                <option disabled selected>-DB-</option>
                <option value="1">SQL</option>
                <option value="2">XML</option>
            </select>
            <button class="delete" type="submit">OK</button>
        </form>
        <h2 class="selectdb-text">Select DB</h2>
        </div>
    </div>
    <div class="line"></div>

    <form class="submitform" method="post" asp-action="AddTask">
        <div class="inputitem">
            <textarea 
                      asp-for="MyTask"
                      value="@Model.MyTask"></textarea>
            <span asp-validation-for="MyTask" class="text-danger"></span>
            @if (Model.id != 0)
            {
                <label class="updateLabel" asp-for="MyTask">UPDATE TASK    <a class="updateLabel-a" asp-action="Index"> ESC</a></label>
            }
            else
            {
                <label asp-for="MyTask">AddTask</label>
            }

        </div>
        <div class="submitpage-btnblock">
            <input class="inputdatatime" type="datetime-local"
                   value="@Model.DueDateString"
                   asp-for="DueDate" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
            <input asp-for="id" type="hidden" value="@Model.id">
            <select asp-for="CategoryId" asp-items="@Model.Category">
                <option value="@Model.Category" disabled selected>-Category-</option>
            </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            @if (Model.id != 0)
            {
                <button class="submitbottomred">Оновити</button>
            }
            else
            {
                <button class="submitbottom">Додати</button>
            }

        </div>
    </form>
    <div class="line"></div>

    <div class="submitform_container">
        <div class="submitform_container_wrapper">
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">Виконані / Пропущені</h4>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.allTaskPast)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>

            </div>
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">В роботу</h4>
                    <p class="resultpage_conteiner_next"></p>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.allTaskNow)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>
            </div>
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">Заплановані</h4>
                    <p class="resultpage_conteiner_nextnow"></p>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.allTaskFuture)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ToDoList/Views/ToDoList/Index.cshtml
@model ToDoList.Models.ToDoListModelVM

@{
    ViewData["Title"] = "Form";
}

<div class="submitpage">
    <div class="submitpage-headerbox">
        <a asp-action="Index">
            <div class="submitpage-headerbox-logobox">
                <img class="submitpage-headerbox-logo" src="~/todoListLogo.svg" />
            </div>
        </a>
        <div class="selectdb">
            <p class="selectdb-text"> змінити сховище</p>
            <form asp-controller="ToDoList" asp-action="SetServise" method="post">
                <select asp-for="Id">
                    <option disabled selected>-DB-</option>
                    <option value="1">SQL</option>
                    <option value="2">XML</option>
                </select>
                <button class="delete" type="submit">OK</button>
            </form>
            <p class="selectdb-text"> пдключено <span>@ViewData["DB"]</span></p>
        </div>
    </div>
    <div class="line"></div>

    <form class="submitform" method="post" asp-action="AddTask">
        <div class="inputitem">
            <textarea asp-for="MyTask" value="@Model.MyTask"></textarea>
            @if (Model.Id != 0)
            {
                <label class="updateLabel" asp-for="MyTask">UPDATE TASK    <a class="updateLabel-a" asp-action="Index"> ESC</a></label>
            }
            else
            {
                <label asp-for="MyTask">AddTask</label>
            }
             <span asp-validation-for="MyTask" class="text-danger"></span>

        </div>
        <div class="submitpage-btnblock">
            <input class="inputdatatime" type="datetime-local"
                   value="@Model.DueDateString"
                   asp-for="DueDate" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
            <input asp-for="Id" type="hidden" value="@Model.Id">
            <select asp-for="CategoryId" asp-items="@Model.Category">
                <option value="@Model.Category" disabled selected>-Category-</option>
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
            @if (Model.Id != 0)
            {
                <button class="submitbottomred">Оновити</button>
            }
            else
            {
                <button class="submitbottom">Додати</button>
            }

        </div>
    </form>
    <div class="line"></div>

    <div class="submitform_container">
        <div class="submitform_container_wrapper">
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">Виконані / Пропущені</h4>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.AllTaskPast)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>

            </div>
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">В роботу</h4>
                    <p class="resultpage_conteiner_next"></p>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.AllTaskNow)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>
            </div>
            <div class="resultpage_conteiner">
                <div class="resultpage_conteiner_title_container">
                    <h4 class="resultpage_conteiner_title">Заплановані</h4>
                    <p class="resultpage_conteiner_nextnow"></p>
                </div>
                <div class="resultpage">
                    @foreach (var i in Model.AllTaskFuture)
                    {
                        <partial name="_OneTask" model="i" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}